import {initializeApp} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signInAnonymously,signOut} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import {getFirestore,collection,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,serverTimestamp,writeBatch} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";

const $=id=>document.getElementById(id); const cfg=window.OSTL_FIREBASE_CONFIG; if(!cfg) throw Error('Missing firebase-config.js');
const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app); const params=new URLSearchParams(location.search);
let S={user:null,role:'spectator',group:null,tid:null,t:null,players:[],scores:[],unsubs:[],hole:1};
const show=id=>['login','home','create','event'].forEach(x=>$(x).classList.toggle('hidden',x!==id));
const toast=m=>{ $('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)};
const status=(m,e=false)=>{$('status').textContent=m;$('status').classList.toggle('error',e)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
const ADMIN_EMAIL_DOMAIN='ozarktravelstein.app';
function usernameToEmail(value){
  const username=String(value||'').trim().toLowerCase();
  if(!/^[a-z0-9._-]{3,30}$/.test(username)) throw Error('Username must be 3–30 characters using letters, numbers, dots, dashes, or underscores.');
  return `${username}@${ADMIN_EMAIL_DOMAIN}`;
}
function groups(el){el.innerHTML=Array.from({length:6},(_,i)=>`<option value="${i+1}">Group ${i+1}</option>`).join('')}
groups($('playerGroup'));groups($('groupSelect'));

async function ensureAuth(){if(auth.currentUser)return auth.currentUser;await signInAnonymously(auth);return auth.currentUser}
async function claimGroup(){const tid=params.get('t'),g=Number(params.get('g')),k=params.get('token');if(!tid||!g||!k)return false;await ensureAuth();await setDoc(doc(db,'tournaments',tid,'claims',auth.currentUser.uid),{role:'group',group:g,token:k,claimedAt:serverTimestamp()},{merge:false});S.role='group';S.group=g;await openEvent(tid);return true}
async function openSpectator(){await ensureAuth();const p=await getDoc(doc(db,'public','active'));if(!p.exists())throw Error('No active tournament has been selected.');S.role='spectator';await openEvent(p.data().tournamentId)}

onAuthStateChanged(auth,async u=>{S.user=u;try{if(params.get('g')){await claimGroup();return}if(params.get('spectator')){await openSpectator();return}if(u&&!u.isAnonymous){S.role='admin';await loadHome()}else{show('login');status('Administrator sign-in required.')}}catch(e){status(e.message,true);show('login')}});
$('loginBtn').onclick=async()=>{try{
  const email=usernameToEmail($('username').value);
  await signInWithEmailAndPassword(auth,email,$('password').value);
  S.role='admin';
  await loadHome();
}catch(e){status(e.code==='auth/invalid-credential'?'Incorrect username or password.':e.message,true)}};
$('spectatorBtn').onclick=()=>location.href='?spectator=1';
$('newBtn').onclick=()=>show('create');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('home'));
$('backBtn').onclick=()=>{S.unsubs.forEach(f=>f());S.unsubs=[];loadHome()};

async function loadHome(){show('home');status('Connected as administrator.');const snap=await getDocs(query(collection(db,'tournaments'),orderBy('date','desc')));$('tournaments').innerHTML=snap.empty?'<p>No tournaments yet.</p>':snap.docs.map(d=>`<button class="secondary full eventBtn" data-id="${d.id}">${esc(d.data().name)} — ${esc(d.data().course||'')}</button>`).join('');document.querySelectorAll('.eventBtn').forEach(b=>b.onclick=()=>openEvent(b.dataset.id))}
$('createBtn').onclick=async()=>{try{const holes=Number($('newHoles').value),pars=Array.from({length:holes},(_,i)=>[4,4,3,5,4,4,3,5,4][i%9]),si=Array.from({length:holes},(_,i)=>i+1);const ref=await addDoc(collection(db,'tournaments'),{name:$('newName').value.trim(),course:$('newCourse').value.trim(),date:$('newDate').value,holes,pars,strokeIndexes:si,handicapSkinHoles:[],blindSkinHoles:[],active:false,adminUid:auth.currentUser.uid,createdAt:serverTimestamp()});await openEvent(ref.id)}catch(e){status(e.message,true)}};

async function openEvent(id){S.tid=id;show('event');S.unsubs.forEach(f=>f());S.unsubs=[];S.unsubs.push(onSnapshot(doc(db,'tournaments',id),x=>{if(!x.exists())return;S.t={id:x.id,...x.data()};renderAll()}));S.unsubs.push(onSnapshot(collection(db,'tournaments',id,'players'),x=>{S.players=x.docs.map(d=>({id:d.id,...d.data()}));renderAll()}));S.unsubs.push(onSnapshot(collection(db,'tournaments',id,'scores'),x=>{S.scores=x.docs.map(d=>({id:d.id,...d.data()}));renderAll()}));status(`Connected • ${S.role}`)}
function allowedAdmin(){return S.role==='admin'}
function renderAll(){if(!S.t)return;$('eventName').textContent=S.t.name;$('eventMeta').textContent=`${S.t.course||''} • ${S.t.date||''} • ${S.t.holes} holes`;$('roleBadge').textContent=S.role==='admin'?'ADMIN':S.role==='group'?`GROUP ${S.group}`:'SPECTATOR';$('players').classList.toggle('hidden',!allowedAdmin()||!document.querySelector('[data-tab="players"]').classList.contains('active'));$('setup').classList.toggle('hidden',!allowedAdmin()||!document.querySelector('[data-tab="setup"]').classList.contains('active'));renderLeader();renderScores();renderPlayers();renderSetup();renderSkins()}

document.querySelectorAll('[data-tab]').forEach((b,i)=>{if(i===0)b.classList.add('active');b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pane').forEach(x=>x.classList.add('hidden'));const id=b.dataset.tab;if((id==='players'||id==='setup')&&!allowedAdmin()){toast('Administrator only');document.querySelector('[data-tab="leader"]').click();return}$(id).classList.remove('hidden');renderAll()}});
function playerNet(p,h,gross){const allowance=Math.round((p.courseHandicap||0)*1);const base=Math.trunc(allowance/(S.t.holes||18)),extra=allowance%(S.t.holes||18),si=S.t.strokeIndexes?.[h-1]||h;return gross-base-(si<=extra?1:0)}
function renderLeader(){let rows=S.players.map(p=>{const ss=S.scores.filter(s=>s.playerId===p.id);const gross=ss.reduce((a,s)=>a+s.gross,0),par=ss.reduce((a,s)=>a+(S.t.pars?.[s.hole-1]||4),0),net=ss.reduce((a,s)=>a+playerNet(p,s.hole,s.gross),0);return{p,thru:ss.length,val:net-par,gross}}).sort((a,b)=>a.val-b.val);$('leader').innerHTML='<h2>Leaderboard</h2>'+rows.map((r,i)=>`<div class="leaderRow"><b>${i+1}</b><span>${esc(r.p.name)}</span><span>${r.thru}</span><b>${r.val>0?'+':''}${r.val||'E'}</b></div>`).join('')}
function renderScores(){const groupsAllowed=S.role==='group'?[S.group]:[1,2,3,4,5,6];$('groupSelect').innerHTML=groupsAllowed.map(g=>`<option value="${g}">Group ${g}</option>`).join('');if(S.role==='group')$('groupSelect').disabled=true;const holes=S.t?.holes||18;$('holeSelect').innerHTML=Array.from({length:holes},(_,i)=>`<option value="${i+1}" ${i+1===S.hole?'selected':''}>Hole ${i+1}</option>`).join('');const g=Number($('groupSelect').value||groupsAllowed[0]),h=Number($('holeSelect').value||S.hole);S.hole=h;const ps=S.players.filter(p=>Number(p.group)===g);$('scoreGrid').innerHTML=ps.length?ps.map(p=>{const old=S.scores.find(s=>s.playerId===p.id&&s.hole===h);return`<div class="scoreplayer"><b>${esc(p.name)}</b><div class="numbers">${Array.from({length:12},(_,i)=>`<button data-p="${p.id}" data-g="${g}" data-v="${i+1}" class="${old?.gross===i+1?'selected':''}">${i+1}</button>`).join('')}</div></div>`}).join(''):'<p>No players in this group.</p>';document.querySelectorAll('.numbers button').forEach(b=>b.onclick=()=>saveScore(b.dataset.p,Number(b.dataset.g),h,Number(b.dataset.v)))}
$('groupSelect').onchange=renderScores;$('holeSelect').onchange=()=>{S.hole=Number($('holeSelect').value);renderScores()};$('prevHole').onclick=()=>{S.hole=Math.max(1,S.hole-1);renderScores()};$('nextHole').onclick=()=>{S.hole=Math.min(S.t.holes,S.hole+1);renderScores()};
async function saveScore(pid,g,h,v){try{const p=S.players.find(x=>x.id===pid);await setDoc(doc(db,'tournaments',S.tid,'scores',`${pid}_${h}`),{playerId:pid,group:g,hole:h,gross:v,updatedBy:auth.currentUser.uid,updatedAt:serverTimestamp()});toast(`${p.name}: ${v}`)}catch(e){toast(e.message)}}
function renderPlayers(){$('playerList').innerHTML=S.players.map(p=>`<div class="player"><b>${esc(p.name)}</b> • HCP ${p.courseHandicap||0} • Group ${p.group}</div>`).join('')}
$('addPlayer').onclick=async()=>{await addDoc(collection(db,'tournaments',S.tid,'players'),{name:$('playerName').value.trim(),courseHandicap:Number($('playerHcp').value||0),group:Number($('playerGroup').value)});$('playerName').value=''};
function renderSetup(){if(!allowedAdmin()||!S.t)return;$('editName').value=S.t.name||'';$('editCourse').value=S.t.course||'';$('editDate').value=S.t.date||'';$('activeEvent').checked=!!S.t.active;$('holeSetup').innerHTML=Array.from({length:S.t.holes},(_,i)=>{const h=i+1;return`<div class="holeRow"><b>Hole ${h}</b><label><input type="checkbox" class="hcpSkin" value="${h}" ${S.t.handicapSkinHoles?.includes(h)?'checked':''}> Handicap</label><label><input type="checkbox" class="blindSkin" value="${h}" ${S.t.blindSkinHoles?.includes(h)?'checked':''}> Blind</label></div>`}).join('')}
$('saveSetup').onclick=async()=>{const active=$('activeEvent').checked;await updateDoc(doc(db,'tournaments',S.tid),{name:$('editName').value,course:$('editCourse').value,date:$('editDate').value,active,handicapSkinHoles:[...document.querySelectorAll('.hcpSkin:checked')].map(x=>Number(x.value)),blindSkinHoles:[...document.querySelectorAll('.blindSkin:checked')].map(x=>Number(x.value))});if(active)await setDoc(doc(db,'public','active'),{tournamentId:S.tid});toast('Saved')};
$('generateLinks').onclick=async()=>{const ts={};for(let g=1;g<=6;g++)ts[`g${g}`]=token();await setDoc(doc(db,'tournaments',S.tid,'access','private'),{groupTokens:ts,updatedAt:serverTimestamp()});renderLinks(ts)};
function renderLinks(ts=null){if(!ts){$('links').innerHTML='<p>Generate links first.</p>';return}const base=location.origin+location.pathname;$('links').innerHTML=Array.from({length:6},(_,i)=>{const g=i+1,u=`${base}?t=${S.tid}&g=${g}&token=${ts['g'+g]}`;return`<div class="linkrow"><b>Group ${g}</b><br><input readonly value="${u}"><button data-copy="${u}">Copy</button></div>`}).join('')+`<div class="linkrow"><b>Spectator</b><br><input readonly value="${base}?spectator=1"><button data-copy="${base}?spectator=1">Copy</button></div>`;document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);toast('Copied')})}
$('clearScores').onclick=async()=>{if(!confirm('Clear every score but keep the tournament, course and players?'))return;const snap=await getDocs(collection(db,'tournaments',S.tid,'scores'));const batch=writeBatch(db);snap.docs.forEach(d=>batch.delete(d.ref));await batch.commit();toast('Scores cleared')};
function skinResults(holes,net){return holes?.map(h=>{const entries=S.players.map(p=>{const s=S.scores.find(x=>x.playerId===p.id&&x.hole===h);return s?{p,v:net?playerNet(p,h,s.gross):s.gross}:null}).filter(Boolean);if(entries.length<S.players.length)return`<div class="skinrow">Hole ${h}: waiting</div>`;const low=Math.min(...entries.map(x=>x.v)),wins=entries.filter(x=>x.v===low);return`<div class="skinrow"><b>Hole ${h}</b>: ${wins.map(x=>esc(x.p.name)).join(', ')} (${low})</div>`}).join('')||'<p>No holes selected.</p>'}
function renderSkins(){if(!S.t)return;$('handicapSkins').innerHTML=skinResults(S.t.handicapSkinHoles,true);$('blindSkins').innerHTML=skinResults(S.t.blindSkinHoles,false);renderLinks()}
